media: platform: dwc: fix compilation errors on dphy driver
Make the functions that are used internally as static and define the
missing function prototype. Fixes the following error

drivers/media/platform/dwc/dw-dphy-rx.c:98:6: error: no previous prototype
for function 'dw_dphy_if_write' [-Werror,-Wmissing-prototypes] void
dw_dphy_if_write(struct dw_dphy_rx *dphy, u32 address, u32 data)

drivers/media/platform/dwc/dw-dphy-rx.c:501:5: error: no previous prototype
for function 'dw_dphy_if_set_idelay' [-Werror,-Wmissing-prototypes] int
dw_dphy_if_set_idelay(struct dw_dphy_rx *dphy, u8 dly, u8 cells)

Fixes: 38a5ec2af715 ("media: platform: dwc: Add DW MIPI DPHY Rx driver")
Signed-off-by: Balamanikandan Gunasundar <balamanikandan.gunasundar@microchip.com>